language: node_js
dist: trusty
node_js:
  - "10"
services:
  - mongodb
script:
  - npm run build
  - npm run test:ci

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
